version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "5000:5000"
    environment: 
      ROUTE_TOKEN: ${ROUTE_TOKEN}
      GEOID_TOKEN: ${GEOID_TOKEN}
      VG_TOKEN: ${VG_TOKEN}
      THEMATIC_TOKEN: ${THEMATIC_TOKEN}
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "8080:8080"
    environment:
      VITE_BASE_URL: "https://${CODESPACE_NAME}-5000.github.dev"
    depends_on:
      - backend